import {BidValue, RaiseValue, Suit} from '@app/shared/models/types.enums';
import {Card, Cards} from '@app/shared/models/card.model';
import {Bid} from '@app/shared/models/bid.model';

export class RaiseStrength {
  suit: Suit;
  raiseValue: RaiseValue;
  dependsOnOffsuit: boolean;
  constructor(_suit: Suit){
    this.suit = _suit;
    this.raiseValue = RaiseValue.zero;
  }
}

export namespace RaiseStrengthHelpers {
  export function GetSupportingStrength(cards: Card[], partnerBid: Bid): RaiseStrength {
    var raiseStrength: RaiseStrength = new RaiseStrength(partnerBid.suit);
    var keyValue: string = Cards.getValue(cards, partnerBid.suit);

    switch (partnerBid.value) {
      // Partner Bid 6
      case BidValue.six:
        switch (keyValue) {
          case "00005": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00006": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00013": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00014": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00103": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00104": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00112": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00113": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "01003": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "01004": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "01012": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "01013": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "01102": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "01103": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "01110": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "10003": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00007": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00015": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00105": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00106": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00114": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01014": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01104": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01111": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10004": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10010": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10011": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10012": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10100": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10101": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11000": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11001": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11002": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11010": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00008": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00016": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00017": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00107": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00115": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00116": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01006": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01015": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01016": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01105": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01106": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01112": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01113": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10006": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10013": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10014": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10015": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10102": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10103": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10110": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10111": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10112": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11003": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11004": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11011": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11012": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11013": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11100": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11101": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00009": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "00018": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "00019": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "00108": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "00109": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "00117": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01008": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01009": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01017": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01018": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01107": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01114": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01115": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10008": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10009": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10016": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10017": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10104": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10105": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10106": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10113": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "10114": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11005": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11006": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11014": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11015": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11102": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11103": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11110": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11111": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11112": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "11113": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = true; break;
          case "01108": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "01116": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "01117": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "10018": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "10107": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "10108": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "10115": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "10116": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "10117": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11007": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11008": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11016": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11017": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11104": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11105": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11106": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11107": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11114": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11115": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "11116": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = false; break;
          case "00118": raiseStrength.raiseValue = RaiseValue.four; raiseStrength.dependsOnOffsuit = true; break;
          default: raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = false; break;
        }
        break;
      // Partner Bid 7
      case BidValue.seven:
        switch (keyValue) {
          case "01012": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01102": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "00005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00006": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00014": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00015": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00112": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00113": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00114": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01004": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01013": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01014": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01103": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01104": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01110": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01111": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10003": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10004": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10010": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10011": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10012": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10100": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10101": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11000": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11001": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11002": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11010": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00105": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "00007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00008": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00016": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00017": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00106": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00107": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00115": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00116": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01006": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01015": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01016": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01105": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01106": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01112": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01113": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "01114": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10006": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10013": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10014": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10015": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10102": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10103": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10110": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10111": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "10112": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11003": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11004": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11011": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11012": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11013": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11100": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "11101": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = true; break;
          case "00009": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "00018": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "00019": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "00108": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "00109": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "00117": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "00118": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01008": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01009": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01017": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01018": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01107": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01108": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01115": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01116": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "01117": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10008": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10009": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10016": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10017": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10018": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10104": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10105": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10106": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10107": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10108": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10113": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10114": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10115": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10116": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "10117": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11005": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11006": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11007": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11008": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11014": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11015": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11016": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11017": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11102": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11103": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11104": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11105": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11106": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11107": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11110": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11111": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11112": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11113": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11114": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11115": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          case "11116": raiseStrength.raiseValue = RaiseValue.three; raiseStrength.dependsOnOffsuit = false; break;
          default: raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = false; break;
        }
        break;
      // Partner Bid 8
      case BidValue.eight:
        switch (keyValue) {
          case "00013": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00112": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "10100": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "10101": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "10110": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "10111": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "11010": raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = true; break;
          case "00014": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "00015": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "00104": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01012": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01102": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01103": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01104": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01105": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01110": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01111": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01112": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "01113": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "10003": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "10004": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "10005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "10010": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "10011": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "10012": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "11000": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "11001": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "11011": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = false; break;
          case "00005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00006": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00105": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00113": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00114": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01004": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01005": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01013": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01014": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01015": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01016": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01106": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01114": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "01115": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10006": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10007": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10013": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10014": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10102": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10103": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10104": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10112": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "10113": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11002": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11003": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11004": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11012": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "11013": raiseStrength.raiseValue = RaiseValue.one; raiseStrength.dependsOnOffsuit = true; break;
          case "00007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00008": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00009": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00016": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00017": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00018": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00019": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00106": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00107": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00108": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00109": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00115": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00116": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00117": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "00118": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01006": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01008": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01009": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01017": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01018": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01107": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01108": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01116": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "01117": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10008": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10009": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10015": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10016": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10017": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10018": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10105": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10106": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10107": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10108": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10114": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10115": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10116": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "10117": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11005": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11006": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11007": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11008": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11014": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11015": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11016": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11017": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11100": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11101": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11102": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11103": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11104": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11105": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11106": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11107": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11110": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11111": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11112": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11113": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11114": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11115": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          case "11116": raiseStrength.raiseValue = RaiseValue.two; raiseStrength.dependsOnOffsuit = false; break;
          default: raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = false; break;
        }
        break;
      default: raiseStrength.raiseValue = RaiseValue.zero; raiseStrength.dependsOnOffsuit = false; break;
    }

    return raiseStrength;
  }
}
